CREATE SEQUENCE public.SUCURSAL_ID MINVALUE 1 INCREMENT 1;

CREATE TABLE public.SUCURSAL
(
    SUCURSAL_ID integer NOT NULL DEFAULT Nextval('public.SUCURSAL_ID'),
    SUCURSAL_ESTADO CHAR(1) NOT NULL,
    SUCURSAL_NOM VARCHAR(100) NOT NULL,
    SUCURSAL_IP VARCHAR(100) NOT NULL,
    SUCURSAL_PATH_DB VARCHAR(100) NOT NULL,
    SUCURSAL_PATH_IMA VARCHAR(100) NOT NULL,
    PRIMARY KEY (SUCURSAL_ID)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

COMMENT ON TABLE public.SUCURSAL IS 'Sucursal';
COMMENT ON COLUMN public.SUCURSAL.SUCURSAL_ID IS 'Código Sucursal';
COMMENT ON COLUMN public.SUCURSAL.SUCURSAL_ESTADO IS 'Tipo Estado';
COMMENT ON COLUMN public.SUCURSAL.SUCURSAL_NOM IS 'Sucursal';
COMMENT ON COLUMN public.SUCURSAL.SUCURSAL_IP IS 'Direccion IP';
COMMENT ON COLUMN public.SUCURSAL.SUCURSAL_PATH_DB IS 'Path DB';
COMMENT ON COLUMN public.SUCURSAL.SUCURSAL_PATH_IMA IS 'Path IMAGEN';

ALTER TABLE public.SUCURSAL OWNER to cul_wally;